/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseModal: typeof import('./src/components/base/BaseModal.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next')['BButtonGroup']
    BCarousel: typeof import('bootstrap-vue-next')['BCarousel']
    BCarouselSlide: typeof import('bootstrap-vue-next')['BCarouselSlide']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavForm: typeof import('bootstrap-vue-next')['BNavForm']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    BToast: typeof import('bootstrap-vue-next')['BToast']
    CallToActionSection: typeof import('./src/components/CallToActionSection.vue')['default']
    Favorites: typeof import('./src/components/navbar/Favorites.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavigationSearch: typeof import('./src/components/navbar/NavigationSearch.vue')['default']
    ShoppingBag: typeof import('./src/components/navbar/ShoppingBag.vue')['default']
    TheFavorites: typeof import('./src/components/navbar/TheFavorites.vue')['default']
    TheNavigationBar: typeof import('./src/components/navbar/TheNavigationBar.vue')['default']
    TheNavigationSearch: typeof import('./src/components/navbar/TheNavigationSearch.vue')['default']
    TheShoppingBag: typeof import('./src/components/navbar/TheShoppingBag.vue')['default']
    TheSignUp: typeof import('./src/components/navbar/TheSignUp.vue')['default']
    TheSliderBanner: typeof import('./src/components/TheSliderBanner.vue')['default']
    TheTheNavigationBar: typeof import('./src/components/navbar/TheTheNavigationBar.vue')['default']
    TheUserDropDown: typeof import('./src/components/navbar/TheUserDropDown.vue')['default']
    UserDropDown: typeof import('./src/components/navbar/UserDropDown.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBColorMode: typeof import('bootstrap-vue-next')['vBColorMode']
  }
}
